CREATE TABLE IF NOT EXISTS clienti (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    randomn_id INT UNSIGNED NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NULL,
    phone VARCHAR(50) NULL,
    status TINYINT(1) NULL DEFAULT 1,
    city VARCHAR(120) NULL,
    address VARCHAR(255) NULL,
    total_orders INT UNSIGNED NOT NULL DEFAULT 0,
    total_paid DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    preferred_courier VARCHAR(120) NULL,
    notes TEXT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_randomn_id (randomn_id),
    INDEX idx_status (status),
    INDEX idx_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE clienti
    ADD COLUMN IF NOT EXISTS randomn_id INT UNSIGNED NULL UNIQUE AFTER id,
    ADD COLUMN IF NOT EXISTS city VARCHAR(120) NULL AFTER phone,
    ADD COLUMN IF NOT EXISTS address VARCHAR(255) NULL AFTER city,
    ADD COLUMN IF NOT EXISTS total_orders INT UNSIGNED NOT NULL DEFAULT 0 AFTER status,
    ADD COLUMN IF NOT EXISTS total_paid DECIMAL(12, 2) NOT NULL DEFAULT 0.00 AFTER total_orders,
    ADD COLUMN IF NOT EXISTS preferred_courier VARCHAR(120) NULL AFTER total_paid,
    ADD COLUMN IF NOT EXISTS notes TEXT NULL AFTER preferred_courier,
    ADD COLUMN IF NOT EXISTS updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;

UPDATE clienti
SET randomn_id = id + 100000
WHERE randomn_id IS NULL;
