CREATE TABLE IF NOT EXISTS marketplace (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    randomn_id INT UNSIGNED NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    platform VARCHAR(60) NOT NULL DEFAULT 'custom',
    account_name VARCHAR(255) NULL,
    account_email VARCHAR(255) NULL,
    api_token TEXT NULL,
    token_status VARCHAR(30) NOT NULL DEFAULT 'active',
    token_plan VARCHAR(20) NOT NULL DEFAULT 'free',
    starts_at DATETIME NULL,
    ends_at DATETIME NULL,
    api_base_url VARCHAR(500) NULL,
    webhook_url VARCHAR(500) NULL,
    sync_mode VARCHAR(40) NOT NULL DEFAULT 'manual',
    products_synced INT UNSIGNED NOT NULL DEFAULT 0,
    requests_today INT UNSIGNED NOT NULL DEFAULT 0,
    offers_sent INT UNSIGNED NOT NULL DEFAULT 0,
    errors_count INT UNSIGNED NOT NULL DEFAULT 0,
    last_sync_at DATETIME NULL,
    last_test_status VARCHAR(30) NULL,
    last_test_message VARCHAR(500) NULL,
    last_test_at DATETIME NULL,
    notes TEXT NULL,
    status TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_marketplace_randomn_id (randomn_id),
    INDEX idx_marketplace_platform (platform),
    INDEX idx_marketplace_token_status (token_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
