<?php

declare(strict_types=1);

/**
 * Genereaza admin/storage/rclone/rclone.conf din furnizorii activi FTP/SFTP.
 *
 * Usage: php admin/tools/generate_rclone_config.php
 */

require dirname(__DIR__) . '/vendor/autoload.php';
require dirname(__DIR__) . '/scripts/supplier_rclone_lib.php';
require dirname(__DIR__) . '/src/Controllers/Produse/import_supplier_lib.php';

$dotenv = Dotenv\Dotenv::createImmutable(dirname(__DIR__));
$dotenv->safeLoad();
$config = require dirname(__DIR__) . '/config/config.php';

Config\Database::getInstance(
    $config['db_host'],
    $config['db_name'],
    $config['db_user'],
    $config['db_pass']
);

$pdo = new PDO(
    'mysql:host=' . $config['db_host'] . ';dbname=' . $config['db_name'] . ';charset=utf8mb4',
    $config['db_user'],
    $config['db_pass']
);
$rows = $pdo->query(
    "SELECT code, connection_type, conn_host, conn_port, conn_username, conn_password, conn_passive, conn_remote_path
     FROM furnizori
     WHERE status = 'active'
       AND connection_type IN ('ftp', 'sftp')
       AND conn_host IS NOT NULL AND conn_host <> ''
       AND conn_username IS NOT NULL AND conn_username <> ''"
)->fetchAll(PDO::FETCH_ASSOC);

if ($rows === []) {
    fwrite(STDERR, "Niciun furnizor FTP/SFTP activ cu credentiale complete.\n");
    exit(1);
}

$targetDir = dirname(__DIR__) . '/storage/rclone';
if (!is_dir($targetDir) && !mkdir($targetDir, 0775, true) && !is_dir($targetDir)) {
    fwrite(STDERR, "Nu pot crea {$targetDir}\n");
    exit(1);
}

$configPath = $targetDir . '/rclone.conf';
if (!is_file($configPath)) {
    file_put_contents($configPath, "# Generated by generate_rclone_config.php\n");
}

$lines = ["# Generated at " . date('c')];
$count = 0;

foreach ($rows as $row) {
    $code = strtoupper(trim((string) ($row['code'] ?? '')));
    if ($code === '') {
        continue;
    }

    $merged = import_furnizori_resolve_credentials([
        'code' => $code,
        'connection_type' => (string) ($row['connection_type'] ?? 'ftp'),
        'conn_host' => (string) ($row['conn_host'] ?? ''),
        'conn_port' => (int) ($row['conn_port'] ?? 0),
        'conn_username' => (string) ($row['conn_username'] ?? ''),
        'conn_password' => (string) ($row['conn_password'] ?? ''),
        'conn_passive' => (int) ($row['conn_passive'] ?? 1),
        'conn_remote_path' => (string) ($row['conn_remote_path'] ?? '/'),
    ]);

    $host = trim((string) ($merged['conn_host'] ?? ''));
    $user = trim((string) ($merged['conn_username'] ?? ''));
    $pass = (string) ($merged['conn_password'] ?? '');
    if ($host === '' || $user === '' || $pass === '') {
        continue;
    }

    $remoteName = strtolower($code);
    $type = ((string) ($merged['connection_type'] ?? 'ftp')) === 'sftp' ? 'sftp' : 'ftp';
    $port = (int) ($merged['conn_port'] ?? ($type === 'sftp' ? 22 : 21));
    $obscured = supplier_rclone_obscure_password($pass);

    $lines[] = '';
    $lines[] = '[' . $remoteName . ']';
    $lines[] = 'type = ' . $type;
    $lines[] = 'host = ' . $host;
    $lines[] = 'user = ' . $user;
    $lines[] = 'pass = ' . $obscured;
    if ($port > 0 && !(($type === 'ftp' && $port === 21) || ($type === 'sftp' && $port === 22))) {
        $lines[] = 'port = ' . $port;
    }
    if ($type === 'ftp') {
        $lines[] = 'explicit_tls = false';
        if (!empty($merged['conn_passive'])) {
            $lines[] = 'no_check_certificate = true';
        }
    }

    $count++;
}

file_put_contents($configPath, implode(PHP_EOL, $lines) . PHP_EOL);
echo "Generat {$configPath} cu {$count} remote(s).\n";

foreach ($rows as $row) {
    $code = strtolower(trim((string) ($row['code'] ?? '')));
    if ($code === '') {
        continue;
    }
    try {
        supplier_rclone_ping_remote($code);
        echo "OK remote: {$code}\n";
    } catch (Throwable $exception) {
        echo "WARN remote {$code}: " . $exception->getMessage() . PHP_EOL;
    }
}
